name: silent_voice
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  riverpod: ^2.6.1
  go_router: ^16.2.1
  google_sign_in: ^6.1.5
  flutter_riverpod: ^2.4.0
  shared_preferences: ^2.2.1
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
